version: 2.1
orbs:
  python: circleci/python@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  windows: circleci/windows@5

executors:
  linux:
    docker:
      - image: cimg/python:3.12
    resource_class: small

commands:
  python-install-pipenv-packages:
    steps:
      - python/install-packages:
          pkg-manager: pipenv
          include-branch-in-cache-key: false
          args: --dev
  install-python-on-windows:
    steps:
      - run:
          name: Install Python 3.12
          command: |
            set -euxo pipefail
            choco feature enable -n allowGlobalConfirmation
            # skip python install if we already have something that's good enough
            if ! python --version | grep -q 'Python 3\.12'; then
              choco upgrade python312 --package-parameters="/NoLockdown"
            fi
            pip install pipenv

jobs:
  python-cache-dependencies:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - python-install-pipenv-packages

workflows:
  build-and-test:
    jobs:
      - python-cache-dependencies:
          name: server cache dependencies linux
          executor: linux
      - python-cache-dependencies:
          name: server cache dependencies windows
          executor:
            name: windows/default
            shell: bash.exe
          pre-steps:
            - install-python-on-windows