description: "The official CircleCI CIMG Python Docker image."
parameters:
  tag:
    description: "The `cimg/python` Docker image version tag."
    type: string
    default: "3.14"
docker:
  - image: cimg/python:<< parameters.tag >>
