description: "The official CircleCI Python Docker image."
parameters:
  tag:
    description: "The `circleci/python` Docker image version tag."
    type: string
    default: "latest"
docker:
  - image: circleci/python:<< parameters.tag >>
